### ISSUE TITLE
Add `twitter:card`

### ISSUE THREAD

**Issue by ewilan-riviere** [Intevel/nuxt-social-tags#1]
Hello! It's a really useful module, thanks!

Could you add `twitter:card` option? From <https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started#started>

This is an example:

```js
{
  hid: 'twitter:card',
  name: 'twitter:card',
  content: 'summary_large_image',
}
```

**Comment by Intevel** [comment]
Updated with the newest release! :D
